apiVersion: v1
kind: Service
metadata:
  name: declarative-service-app
spec:
  selector:
    app: declarative-deployment-app
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer